name: hello world!
on:
  push:
    branches:
      - master
jobs:
  hello_world_jobs:
    runs-on: ubuntu-18.04
    steps:
      - name: say hello
        run: |
          echo "hello world!"
      - name: time is 
        run: |
          echo "date is"
